### ISSUE TITLE
wgpu error: Validation Error

### ISSUE THREAD

**Issue by fgadaleta** [gfx-rs/naga#2555] opened 2023-10-12 15:34 UTC
```
2023-10-12T15:24:02.928970Z ERROR wgpu::backend::direct: Shader translation error for stage ShaderStages(FRAGMENT): gsamplerCubeArrayShadow isn't supported in textureGrad, textureLod or texture with bias    
2023-10-12T15:24:02.929004Z ERROR wgpu::backend::direct: Please report it to https://github.com/gfx-rs/naga    
2023-10-12T15:24:02.929046Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (0)' panicked at /home/frag/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:3019:5:
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `pbr_opaque_mesh_pipeline`
    Internal error in ShaderStages(FRAGMENT) shader: gsamplerCubeArrayShadow isn't supported in textureGrad, textureLod or texture with bias


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::render_resource::pipeline_cache::PipelineCache::process_pipeline_queue_system`!
thread 'Compute Task Pool (0)' panicked at /home/frag/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.11.1/src/pipelined_rendering.rs:143:45:
called `Result::unwrap()` on an `Err` value: RecvError
```

rustc version

```
rustc --version
rustc 1.75.0-nightly (475c71da0 2023-10-11)
```

**Comment by teoxoy** [comment] 2023-10-12 16:43
Thanks for the report!
This is a duplicate of https://github.com/gfx-rs/naga/issues/1619.

**Closed by teoxoy** 2023-10-12 16:43 UTC
