### ISSUE TITLE
Poor error message when dereferencing non-reference

### ISSUE THREAD

**Issue by HactarCE** [gfx-rs/naga#2091] opened 2022-10-19 15:17 UTC
Compiling this shader module:
```wgsl
@group(0) @binding(0) var<storage, read> a: array<f32>;

@compute
@workgroup_size(64)
fn main(@builtin(global_invocation_id) global_invocation_id: vec3<u32>) {
    arrayLength(a); // should be `&a`
}
```
produces this error:
```
Shader validation error: 
   ┌─ shaders/example.wgsl:1:26
   │
1  │ @group(0) @binding(0) var<storage, read> a: array<f32>;
   │                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ naga::Expression [3]


    Entry point main at Compute is invalid
    Expression [3] is invalid
    Loading of [1] can't be done
```

This error message is very confusing; I think it should point to the line with `arrayLength(a)` because that's more likely to be where the error is.

**Comment by teoxoy** [comment] 2022-11-17 11:12
closing as duplicate of #2089

**Closed by teoxoy** 2022-11-17 11:12 UTC
Labels: lang: WGSL, area: front-end, kind: diagnostics
