### ISSUE TITLE
wgsl array of atomics bug on metal

### ISSUE THREAD

**Issue by Ku95** [gfx-rs/naga#2008] opened 2022-07-15 07:28 UTC
I am receiving the following validation error while trying to compile this wgsl shader.

```wgsl
struct Parameters {
    child_index: atomic<i32>;
    final_indices:  array<atomic<i32>, 4>;
};

@group(0) @binding(0)
var<storage, read_write> parameters: Parameters;

fn child_index() -> i32 {
    return atomicAdd(&parameters.child_index, 1);
}

fn final_index(lod: u32) -> i32 {
    return atomicAdd(&parameters.final_indices[lod], 1);
}
```

```
    Internal error: Metal: program_source:70:47: error: cannot take the address of an rvalue of type 'metal::uint' (aka 'unsigned int')
    int _e8 = metal::atomic_exchange_explicit(&uint(lod_1) < 4 ? parameters.final_indices.inner[lod_1] : DefaultConstructible(), 0, metal::memory_order_relaxed);
                                              ^~~~~~~~~~~~
```

**Comment by cwfitzgerald** [comment] 2022-10-22 07:46
Dupe of #1848

**Closed by cwfitzgerald** 2022-10-22 07:46 UTC
Labels: kind: bug, lang: Metal, area: back-end
