### ISSUE TITLE
[glsl-in] Function [15] 'FXAA' is invalid

### ISSUE THREAD

**Issue by magcius** [gfx-rs/naga#1035] opened 2021-06-26 16:04 UTC
```
Function [15] 'FXAA' is invalid
Expression [15] is invalid
Not a global variable
```

Shader source:

```glsl

#version 440 core
precision mediump float;
#define FRAG
#define attribute in
#define varying in
#define mainPS main
#define VIEWPORT_ORIGIN_TL 1
#define gl_VertexID gl_VertexIndex


#define gl_FragColor o_color
layout(location = 0) out vec4 o_color;


struct Mat4x4 { vec4 mx; vec4 my; vec4 mz; vec4 mw; };
struct Mat4x3 { vec4 mx; vec4 my; vec4 mz; };
struct Mat4x2 { vec4 mx; vec4 my; };

vec3 Mat4x3GetCol0(Mat4x3 m) { return vec3(m.mx.x, m.my.x, m.mz.x); }
vec3 Mat4x3GetCol1(Mat4x3 m) { return vec3(m.mx.y, m.my.y, m.mz.y); }
vec3 Mat4x3GetCol2(Mat4x3 m) { return vec3(m.mx.z, m.my.z, m.mz.z); }
vec3 Mat4x3GetCol3(Mat4x3 m) { return vec3(m.mx.w, m.my.w, m.mz.w); }

vec4 Mul(Mat4x4 m, vec4 v) { return vec4(dot(m.mx, v), dot(m.my, v), dot(m.mz, v), dot(m.mw, v)); }
vec3 Mul(Mat4x3 m, vec4 v) { return vec3(dot(m.mx, v), dot(m.my, v), dot(m.mz, v)); }
vec2 Mul(Mat4x2 m, vec4 v) { return vec2(dot(m.mx, v), dot(m.my, v)); }

vec4 Mul(vec3 v, Mat4x3 m) {
return vec4(
    dot(Mat4x3GetCol0(m), v),
    dot(Mat4x3GetCol1(m), v),
    dot(Mat4x3GetCol2(m), v),
    dot(Mat4x3GetCol3(m), v)
);
}

/* void Fma(inout Mat4x3 d, Mat4x3 m, float s) { d.mx += m.mx * s; d.my += m.my * s; d.mz += m.mz * s; } */

Mat4x4 _Mat4x4(float n) { Mat4x4 o; o.mx = vec4(n, 0.0, 0.0, 0.0); o.my = vec4(0.0, n, 0.0, 0.0); o.mz = vec4(0.0, 0.0, n, 0.0); o.mw = vec4(0.0, 0.0, 0.0, n); return o; }
Mat4x4 _Mat4x4(Mat4x3 m) { Mat4x4 o = _Mat4x4(1.0); o.mx = m.mx; o.my = m.my; o.mz = m.mz; return o; }
Mat4x4 _Mat4x4(Mat4x2 m) { Mat4x4 o = _Mat4x4(1.0); o.mx = m.mx; o.my = m.my; return o; }

Mat4x3 _Mat4x3(float n) { Mat4x3 o; o.mx = vec4(n, 0.0, 0.0, 0.0); o.my = vec4(0.0, n, 0.0, 0.0); o.mz = vec4(0.0, 0.0, n, 0.0); return o; }
Mat4x3 _Mat4x3(Mat4x4 m) { Mat4x3 o; o.mx = m.mx; o.my = m.my; o.mz = m.mz; return o; }


layout(std140, set = 0, binding = 0) uniform  ub_Params {
    vec4 u_Misc[1];
};
#define u_InvResolution (u_Misc[0].xy)

layout(set = 1, binding = 0) uniform texture2D T_u_Texture;
layout(set = 1, binding = 1) uniform sampler S_u_Texture;

layout(location = 0) in vec2 v_TexCoord;
float MonochromeNTSC(vec3 t_Color) {
    return dot(t_Color.rgb, vec3(0.299, 0.587, 0.114));
}
vec4 FXAA(texture2D T_P_t_Texture, sampler S_P_t_Texture, in vec2 t_PixelCenter, in vec2 t_InvResolution) {
    float lumaMM = MonochromeNTSC(texture(sampler2D(T_P_t_Texture, S_P_t_Texture), t_PixelCenter.xy).rgb);
#if 0
    vec2 t_PixelTopLeft = t_PixelCenter.xy - t_InvResolution.xy * 0.5;
    float lumaNW = MonochromeNTSC(texture      (sampler2D(T_P_t_Texture, S_P_t_Texture), t_PixelTopLeft.xy)             .rgb);
    float lumaNE = MonochromeNTSC(textureOffset(sampler2D(T_P_t_Texture, S_P_t_Texture), t_PixelTopLeft.xy, ivec2(1, 0)).rgb);
    float lumaSW = MonochromeNTSC(textureOffset(sampler2D(T_P_t_Texture, S_P_t_Texture), t_PixelTopLeft.xy, ivec2(0, 1)).rgb);
    float lumaSE = MonochromeNTSC(textureOffset(sampler2D(T_P_t_Texture, S_P_t_Texture), t_PixelTopLeft.xy, ivec2(1, 1)).rgb);
#else
    vec2 t_PixelSize = t_InvResolution.xy * 0.5;
    float lumaNW = MonochromeNTSC(texture(sampler2D(T_P_t_Texture, S_P_t_Texture), t_PixelCenter.xy + t_PixelSize * vec2(-1.0, -1.0)).rgb);
    float lumaNE = MonochromeNTSC(texture(sampler2D(T_P_t_Texture, S_P_t_Texture), t_PixelCenter.xy + t_PixelSize * vec2( 1.0, -1.0)).rgb);
    float lumaSW = MonochromeNTSC(texture(sampler2D(T_P_t_Texture, S_P_t_Texture), t_PixelCenter.xy + t_PixelSize * vec2(-1.0,  1.0)).rgb);
    float lumaSE = MonochromeNTSC(texture(sampler2D(T_P_t_Texture, S_P_t_Texture), t_PixelCenter.xy + t_PixelSize * vec2( 1.0,  1.0)).rgb);
#endif
    vec2 dir; 
    dir.x = -((lumaNW + lumaNE) - (lumaSW + lumaSE));
    dir.y =  ((lumaNW + lumaSW) - (lumaNE + lumaSE));
    const float FXAA_REDUCE_MIN = 1.0/128.0;
    const float FXAA_REDUCE_MUL = 1.0/8.0;
    const float FXAA_SPAN_MAX = 8.0;
    float dirReduce = max(
        (lumaNW + lumaNE + lumaSW + lumaSE) * (0.25 * FXAA_REDUCE_MUL),
        FXAA_REDUCE_MIN);
    float rcpDirMin = 1.0/(min(abs(dir.x), abs(dir.y)) + dirReduce);
    dir = min(vec2( FXAA_SPAN_MAX,  FXAA_SPAN_MAX), max(vec2(-FXAA_SPAN_MAX, -FXAA_SPAN_MAX), dir * rcpDirMin)) * u_InvResolution.xy;
    float lumaMin = min(lumaMM, min(min(lumaNW, lumaNE), min(lumaSW, lumaSE)));
    float lumaMax = max(lumaMM, max(max(lumaNW, lumaNE), max(lumaSW, lumaSE)));
    vec4 rgbA = (1.0/2.0) * (
        texture(sampler2D(T_P_t_Texture, S_P_t_Texture), t_PixelCenter.xy + dir * (1.0/3.0 - 0.5)) +
        texture(sampler2D(T_P_t_Texture, S_P_t_Texture), t_PixelCenter.xy + dir * (2.0/3.0 - 0.5)));
    vec4 rgbB = rgbA * (1.0/2.0) + (1.0/4.0) * (
        texture(sampler2D(T_P_t_Texture, S_P_t_Texture), t_PixelCenter.xy + dir * (0.0/3.0 - 0.5)) +
        texture(sampler2D(T_P_t_Texture, S_P_t_Texture), t_PixelCenter.xy + dir * (3.0/3.0 - 0.5)));
    float lumaB = MonochromeNTSC(rgbB.rgb);
    vec4 rgbOutput = ((lumaB < lumaMin) || (lumaB > lumaMax)) ? rgbA : rgbB;
    return rgbOutput;
}
void main() {
    gl_FragColor.rgba = FXAA(T_u_Texture, S_u_Texture, v_TexCoord.xy, u_InvResolution.xy);
}
```

**Comment by kvark** [comment] 2021-06-26 16:42
Basically a dupe of #950. Closing

**Closed by kvark** 2021-06-26 16:42 UTC
