### ISSUE TITLE
front_facing not working maybe

### ISSUE THREAD

**Issue by martinken** [gfx-rs/naga#769] opened 2021-04-24 14:21 UTC
Apologies if this is the wrong place to report this, if so please just let me know. Tested on firefox nightly, webGPU, on windows 10 as of April 24th 2021. When using front_facing as part of an input struct 

`[[builtin(front_facing)]] frontFacing: bool`

the line 

`if (!input.frontFacing) { normal = -normal; }`

doesn't seem to work properly. Oddly enough if I do 

`if (input.frontFacing == false) { normal = -normal; }`

firefox seems to work fine, but it breaks chrome (see https://bugs.chromium.org/p/tint/issues/detail?id=743)

As of April 24th this example shows the issue as the stream lines rising up should be colored and lighted but are black.

https://kitware.github.io/vtk-js/examples/SceneExplorer/index.html?fileURL=https://data.kitware.com/api/v1/file/58780b8c8d777f05f44b141f/download

which should look like

![image](https://user-images.githubusercontent.com/7387719/115961908-9722b680-a4e6-11eb-9816-dca2b3287e16.png)

**Comment by kvark** [comment] 2021-04-24 22:54
Thank you for filing! Would you be able to record an [API Trace](https://github.com/gfx-rs/wgpu/wiki/Debugging-wgpu-Applications#tracing-infrastructure) and attach it here, zipped? This would allow us to investigate quickly.

**Comment by martinken** [comment] 2021-04-26 13:07
Sure, this is from today's Firefox Nightly

[frontfacing_trace.zip](https://github.com/gfx-rs/naga/files/6377235/frontfacing_trace.zip)

**Comment by kvark** [comment] 2021-04-27 05:04
I wasn't able to replay this in RenderDoc, unfortunately. But I did notice that the generated shader looked weird wrt the boolean negation. So this leads me to believe the issue is now fixed in f77abdb15691289dd517b2ace2a08c010f578d9d.
The next FF wgpu update will pick it up.

**Closed by kvark** 2021-04-27 05:04 UTC
