### ISSUE TITLE
Failure to generate code for WGSL array<> accesses

### ISSUE THREAD

**Issue by blakej11** [gfx-rs/naga#664] opened 2021-04-05 06:30 UTC
While playing around with WGSL arrays, I found a fairly minimal piece of code that would compile successfully with the Metal backend, but would fail for a couple different reasons with the GLSL and SPIR-V backends:

```
const offs : array<f32, 1> = array<f32, 1>( f32(0.0) );

[[stage(compute), workgroup_size(64)]]
fn main() {
    var off : f32 = offs[0];
}
```

When compiling to GLSL, this would fail with:
```
internal error: entered unreachable code: naga/src/back/glsl/mod.rs:638:34
```
The code that generated that error has a comment saying "Panics if `ArraySize::Constant` has a constant that isn't a uint". And indeed, if I change the `, 1`s to `, 1u`s in the `array` declaration, it works fine.

When compiling to SPIR-V, this would fail with:
```
[DEBUG naga::valid::function] var LocalVariable { name: Some("off"), ty: [1], init: None }
[ERROR naga::back::spv::writer] Unable to access Array { base: [1], size: Constant([1]), stride: None }
```
The code that emitted that error has a comment "TODO: support `crate::TypeInner::Array { .. }` ?"

This was with the current snapshot of naga (commit 91e08b252aa3561c2b5a0cda574923732c7855ef).

I'm only using the Metal backend (via wgpu-rs), so neither of these problems actually affect me; I just filed this because I tripped over the issues while trying to debug my own problems and they seemed odd. I recognize that this package is under active development, so if these kinds of reports are unhelpful in the current stage of things I'm happy to not bother with filing them.

**Comment by kvark** [comment] 2021-04-07 16:42
SPIRV backend is filed separately as #635

**Comment by JCapucho** [comment] 2021-08-20 13:47
Closing this since neither the glsl nor spirv backend seem to reproduce

**Closed by JCapucho** 2021-08-20 13:47 UTC
Labels: kind: bug, lang: SPIR-V, area: back-end, lang: GLSL
