### ISSUE TITLE
Naga fails to detect invalid SPIR-V module

### ISSUE THREAD

**Issue by HeroicKatora** [gfx-rs/naga#1414] opened 2021-09-21 18:42 UTC
The following module triggers a core validation error but is not detected by Naga (and when used in wgpu the module is then emitted, still containing the same validation error).

```text
[2021-09-21T18:28:13Z ERROR wgpu_hal::vulkan::instance] VALIDATION [UNASSIGNED-CoreValidation-Shader-InconsistentSpirv (0x6bbb14)]
    	Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x7f2d9ca46978, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Structure id 24 decorated as Block for variable in Uniform storage class must follow relaxed uniform buffer layout rules: member 0 contains an array with stride 8 not satisfying alignment to 16
      %PaintCoordinates = OpTypeStruct %_arr_v2float_uint_4_0 %_arr_v2float_uint_4_1
```

[box.vert.gz](https://github.com/gfx-rs/naga/files/7205415/vert.frag.gz) (Sorry, I typod the name upon zipping. It's a vertex shader, not a fragment shader. But that shouldn't matter anyways.)

Disassembled:
<details>
<pre>
; SPIR-V
; Version: 1.0
; Generator: Google Shaderc over Glslang; 10
; Bound: 137
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %main "main" %vertPosition %_ %uv
               OpSource GLSL 450
               OpSourceExtension "GL_EXT_scalar_block_layout"
               OpSourceExtension "GL_GOOGLE_cpp_style_line_directive"
               OpSourceExtension "GL_GOOGLE_include_directive"
               OpName %main "main"
               OpName %rect_selection_i1_ "rect_selection(i1;"
               OpName %i "i"
               OpName %rect_position_i1_ "rect_position(i1;"
               OpName %i_0 "i"
               OpName %v "v"
               OpName %PaintCoordinates "PaintCoordinates"
               OpMemberName %PaintCoordinates 0 "rect_selection"
               OpMemberName %PaintCoordinates 1 "rect_position"
               OpName %paint_coordinates "paint_coordinates"
               OpName %v_0 "v"
               OpName %innerUv "innerUv"
               OpName %param "param"
               OpName %param_0 "param"
               OpName %vertPosition "vertPosition"
               OpName %param_1 "param"
               OpName %param_2 "param"
               OpName %innerPos "innerPos"
               OpName %param_3 "param"
               OpName %param_4 "param"
               OpName %param_5 "param"
               OpName %param_6 "param"
               OpName %glslPos "glslPos"
               OpName %gl_PerVertex "gl_PerVertex"
               OpMemberName %gl_PerVertex 0 "gl_Position"
               OpMemberName %gl_PerVertex 1 "gl_PointSize"
               OpMemberName %gl_PerVertex 2 "gl_ClipDistance"
               OpMemberName %gl_PerVertex 3 "gl_CullDistance"
               OpName %_ ""
               OpName %uv "uv"
               OpDecorate %_arr_v2float_uint_4_0 ArrayStride 8
               OpDecorate %_arr_v2float_uint_4_1 ArrayStride 8
               OpMemberDecorate %PaintCoordinates 0 Offset 0
               OpMemberDecorate %PaintCoordinates 1 Offset 32
               OpDecorate %PaintCoordinates Block
               OpDecorate %paint_coordinates DescriptorSet 0
               OpDecorate %paint_coordinates Binding 0
               OpDecorate %vertPosition Location 0
               OpMemberDecorate %gl_PerVertex 0 BuiltIn Position
               OpMemberDecorate %gl_PerVertex 1 BuiltIn PointSize
               OpMemberDecorate %gl_PerVertex 2 BuiltIn ClipDistance
               OpMemberDecorate %gl_PerVertex 3 BuiltIn CullDistance
               OpDecorate %gl_PerVertex Block
               OpDecorate %uv Location 0
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
        %int = OpTypeInt 32 1
%_ptr_Function_int = OpTypePointer Function %int
      %float = OpTypeFloat 32
    %v2float = OpTypeVector %float 2
         %10 = OpTypeFunction %v2float %_ptr_Function_int
       %uint = OpTypeInt 32 0
     %uint_4 = OpConstant %uint 4
%_arr_v2float_uint_4 = OpTypeArray %v2float %uint_4
%_ptr_Function__arr_v2float_uint_4 = OpTypePointer Function %_arr_v2float_uint_4
%_arr_v2float_uint_4_0 = OpTypeArray %v2float %uint_4
%_arr_v2float_uint_4_1 = OpTypeArray %v2float %uint_4
%PaintCoordinates = OpTypeStruct %_arr_v2float_uint_4_0 %_arr_v2float_uint_4_1
%_ptr_Uniform_PaintCoordinates = OpTypePointer Uniform %PaintCoordinates
%paint_coordinates = OpVariable %_ptr_Uniform_PaintCoordinates Uniform
      %int_0 = OpConstant %int 0
%_ptr_Uniform_v2float = OpTypePointer Uniform %v2float
      %int_1 = OpConstant %int 1
      %int_2 = OpConstant %int 2
      %int_3 = OpConstant %int 3
%_ptr_Function_v2float = OpTypePointer Function %v2float
%_ptr_Input_v2float = OpTypePointer Input %v2float
%vertPosition = OpVariable %_ptr_Input_v2float Input
     %uint_0 = OpConstant %uint 0
%_ptr_Input_float = OpTypePointer Input %float
     %uint_1 = OpConstant %uint 1
    %float_2 = OpConstant %float 2
%_ptr_Function_float = OpTypePointer Function %float
    %float_1 = OpConstant %float 1
    %v4float = OpTypeVector %float 4
%_arr_float_uint_1 = OpTypeArray %float %uint_1
%gl_PerVertex = OpTypeStruct %v4float %float %_arr_float_uint_1 %_arr_float_uint_1
%_ptr_Output_gl_PerVertex = OpTypePointer Output %gl_PerVertex
          %_ = OpVariable %_ptr_Output_gl_PerVertex Output
    %float_0 = OpConstant %float 0
%_ptr_Output_v4float = OpTypePointer Output %v4float
%_ptr_Output_v2float = OpTypePointer Output %v2float
         %uv = OpVariable %_ptr_Output_v2float Output
       %main = OpFunction %void None %3
          %5 = OpLabel
    %innerUv = OpVariable %_ptr_Function_v2float Function
      %param = OpVariable %_ptr_Function_int Function
    %param_0 = OpVariable %_ptr_Function_int Function
    %param_1 = OpVariable %_ptr_Function_int Function
    %param_2 = OpVariable %_ptr_Function_int Function
   %innerPos = OpVariable %_ptr_Function_v2float Function
    %param_3 = OpVariable %_ptr_Function_int Function
    %param_4 = OpVariable %_ptr_Function_int Function
    %param_5 = OpVariable %_ptr_Function_int Function
    %param_6 = OpVariable %_ptr_Function_int Function
    %glslPos = OpVariable %_ptr_Function_v2float Function
               OpStore %param %int_0
         %64 = OpFunctionCall %v2float %rect_selection_i1_ %param
               OpStore %param_0 %int_1
         %66 = OpFunctionCall %v2float %rect_selection_i1_ %param_0
         %71 = OpAccessChain %_ptr_Input_float %vertPosition %uint_0
         %72 = OpLoad %float %71
         %73 = OpCompositeConstruct %v2float %72 %72
         %74 = OpExtInst %v2float %1 FMix %64 %66 %73
               OpStore %param_1 %int_3
         %76 = OpFunctionCall %v2float %rect_selection_i1_ %param_1
               OpStore %param_2 %int_2
         %78 = OpFunctionCall %v2float %rect_selection_i1_ %param_2
         %79 = OpAccessChain %_ptr_Input_float %vertPosition %uint_0
         %80 = OpLoad %float %79
         %81 = OpCompositeConstruct %v2float %80 %80
         %82 = OpExtInst %v2float %1 FMix %76 %78 %81
         %84 = OpAccessChain %_ptr_Input_float %vertPosition %uint_1
         %85 = OpLoad %float %84
         %86 = OpCompositeConstruct %v2float %85 %85
         %87 = OpExtInst %v2float %1 FMix %74 %82 %86
               OpStore %innerUv %87
               OpStore %param_3 %int_0
         %90 = OpFunctionCall %v2float %rect_position_i1_ %param_3
               OpStore %param_4 %int_1
         %92 = OpFunctionCall %v2float %rect_position_i1_ %param_4
         %93 = OpAccessChain %_ptr_Input_float %vertPosition %uint_0
         %94 = OpLoad %float %93
         %95 = OpCompositeConstruct %v2float %94 %94
         %96 = OpExtInst %v2float %1 FMix %90 %92 %95
               OpStore %param_5 %int_3
         %98 = OpFunctionCall %v2float %rect_position_i1_ %param_5
               OpStore %param_6 %int_2
        %100 = OpFunctionCall %v2float %rect_position_i1_ %param_6
        %101 = OpAccessChain %_ptr_Input_float %vertPosition %uint_0
        %102 = OpLoad %float %101
        %103 = OpCompositeConstruct %v2float %102 %102
        %104 = OpExtInst %v2float %1 FMix %98 %100 %103
        %105 = OpAccessChain %_ptr_Input_float %vertPosition %uint_1
        %106 = OpLoad %float %105
        %107 = OpCompositeConstruct %v2float %106 %106
        %108 = OpExtInst %v2float %1 FMix %96 %104 %107
               OpStore %innerPos %108
        %112 = OpAccessChain %_ptr_Function_float %innerPos %uint_0
        %113 = OpLoad %float %112
        %115 = OpAccessChain %_ptr_Function_float %innerPos %uint_1
        %116 = OpLoad %float %115
        %117 = OpFSub %float %float_1 %116
        %118 = OpCompositeConstruct %v2float %113 %117
        %119 = OpVectorTimesScalar %v2float %118 %float_2
        %120 = OpCompositeConstruct %v2float %float_1 %float_1
        %121 = OpFSub %v2float %119 %120
               OpStore %glslPos %121
        %127 = OpLoad %v2float %glslPos
        %129 = OpCompositeExtract %float %127 0
        %130 = OpCompositeExtract %float %127 1
        %131 = OpCompositeConstruct %v4float %129 %130 %float_0 %float_1
        %133 = OpAccessChain %_ptr_Output_v4float %_ %int_0
               OpStore %133 %131
        %136 = OpLoad %v2float %innerUv
               OpStore %uv %136
               OpReturn
               OpFunctionEnd
%rect_selection_i1_ = OpFunction %v2float None %10
          %i = OpFunctionParameter %_ptr_Function_int
         %13 = OpLabel
          %v = OpVariable %_ptr_Function__arr_v2float_uint_4 Function
         %29 = OpAccessChain %_ptr_Uniform_v2float %paint_coordinates %int_0 %int_0
         %30 = OpLoad %v2float %29
         %32 = OpAccessChain %_ptr_Uniform_v2float %paint_coordinates %int_0 %int_1
         %33 = OpLoad %v2float %32
         %35 = OpAccessChain %_ptr_Uniform_v2float %paint_coordinates %int_0 %int_2
         %36 = OpLoad %v2float %35
         %38 = OpAccessChain %_ptr_Uniform_v2float %paint_coordinates %int_0 %int_3
         %39 = OpLoad %v2float %38
         %40 = OpCompositeConstruct %_arr_v2float_uint_4 %30 %33 %36 %39
               OpStore %v %40
         %41 = OpLoad %int %i
         %43 = OpAccessChain %_ptr_Function_v2float %v %41
         %44 = OpLoad %v2float %43
               OpReturnValue %44
               OpFunctionEnd
%rect_position_i1_ = OpFunction %v2float None %10
        %i_0 = OpFunctionParameter %_ptr_Function_int
         %16 = OpLabel
        %v_0 = OpVariable %_ptr_Function__arr_v2float_uint_4 Function
         %48 = OpAccessChain %_ptr_Uniform_v2float %paint_coordinates %int_1 %int_0
         %49 = OpLoad %v2float %48
         %50 = OpAccessChain %_ptr_Uniform_v2float %paint_coordinates %int_1 %int_1
         %51 = OpLoad %v2float %50
         %52 = OpAccessChain %_ptr_Uniform_v2float %paint_coordinates %int_1 %int_2
         %53 = OpLoad %v2float %52
         %54 = OpAccessChain %_ptr_Uniform_v2float %paint_coordinates %int_1 %int_3
         %55 = OpLoad %v2float %54
         %56 = OpCompositeConstruct %_arr_v2float_uint_4 %49 %51 %53 %55
               OpStore %v_0 %56
         %57 = OpLoad %int %i_0
         %58 = OpAccessChain %_ptr_Function_v2float %v_0 %57
         %59 = OpLoad %v2float %58
               OpReturnValue %59
               OpFunctionEnd
</pre></details>

## Details

It seems to refer to the rules here: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#interfaces-resources-standard-layout

**Comment by HeroicKatora** [comment] 2021-09-21 18:45
Not super relevant for this issue but this module was produced by `shaderc` using the code:

<details>

```glsl
#version 450
#extension GL_EXT_scalar_block_layout : require
layout (location = 0) in vec2 vertPosition;
layout (location = 0) out vec2 uv;

layout (set = 0, binding = 0, std430) uniform PaintCoordinates {
  /* Positions in clockwise rotation starting at top-left. */
  // HACK(naga-1400) if we use arrays vec2[4], we violate Vulkan requirements of alignment.
  // if we use mat4x2 then naga miscalculates the layout and we end up getting overlapping fields.
  // So we use a poor mans array .. .. .
  vec2 rect_selection[4];
  vec2 rect_position[4];
} paint_coordinates;

// HACK(naga-1400)
vec2 rect_selection(int i) {
  vec2 v [4] = { 
    paint_coordinates.rect_selection[0],
    paint_coordinates.rect_selection[1],
    paint_coordinates.rect_selection[2],
    paint_coordinates.rect_selection[3],
  };

  return v[i];
}
vec2 rect_position(int i) {
  vec2 v [4] = { 
    paint_coordinates.rect_position[0],
    paint_coordinates.rect_position[1],
    paint_coordinates.rect_position[2],
    paint_coordinates.rect_position[3],
  };

  return v[i];
}

void main() {
  // Top-left based position (coordinates as in the image package).
  vec2 innerUv = mix(
    mix(rect_selection(0), rect_selection(1), vertPosition.x),
    mix(rect_selection(3), rect_selection(2), vertPosition.x),
    vertPosition.y);

  vec2 innerPos = mix(
    mix(rect_position(0), rect_position(1), vertPosition.x),
    mix(rect_position(3), rect_position(2), vertPosition.x),
    vertPosition.y);

  vec2 glslPos = 2.0*vec2(innerPos.x, 1.0 - innerPos.y) - 1.0;

  gl_Position = vec4(glslPos, 0.0, 1.0);
  uv = innerUv;
}
```

</details>

**Comment by teoxoy** [comment] 2022-04-08 14:36
This is a duplicate of #1299 (while that one mentions WGSL, it's not WGSL specific).

We need to validate array stride to be at least 16 for uniform buffers.

**Closed** 2022-04-10 05:35 UTC
Labels: kind: bug, lang: SPIR-V
