### ISSUE TITLE
WGSL shader converts to inconsistent SPIR-V

### ISSUE THREAD

**Issue by bonsairobo** [gfx-rs/naga#719] opened 2021-04-14 06:39 UTC
There is a downstream effect on my application that uses wgpu: https://github.com/gfx-rs/wgpu/issues/1321

The result of the inconsistent SPIR-V is that my application segfaults.

## Steps to Reproduce

On Linux or Windows (because they use Vulkan by default):

```
git clone https://github.com/bonsairobo/wgpu-isosurface
cd wgpu-isosurface
cargo run
```

## Error Log

```
[2021-04-12T01:36:52Z ERROR gfx_backend_vulkan] 
    VALIDATION [UNASSIGNED-CoreValidation-Shader-InconsistentSpirv (0x6bbb14)] : Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x55c4f04e76b8, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: ID 65[%65] has not been defined
      %66 = OpCompositeExtract %float %65 0
    
    object info: (type: DEVICE, hndl: 0x55c4f04e76b8)
```

## The SPIR-V

I've attached the actual SPIR-V generated by naga on rev `142038c8`.

Input WGSL: https://github.com/bonsairobo/wgpu-isosurface/blob/main/src/dual_contour.wgsl

Output SPIR-V: [dual_contour.spv.txt](https://github.com/gfx-rs/naga/files/6308658/dual_contour.spv.txt)

**Comment by kvark** [comment] 2021-04-14 15:02
Thank you for filing this!
Looks to be a dupe of #635 (cc @acowley )

**Closed by kvark** 2021-04-14 15:02 UTC
Labels: area: back-end, kind: bug, lang: SPIR-V
