### ISSUE TITLE
[msl-out] Shadowed variables are not allowed and so need to be renamed

### ISSUE THREAD

**Issue by superdump** [gfx-rs/naga#1057] opened 2021-07-01 19:35 UTC
It seems in wgsl that shadowing of variables is allowed, something like:

```rust
let a: u8 = 1;
let a: f32 = 1.0;
```

This works fine when running with the Vulkan backend, but metal does not support this shadowing of variables and so the variables will need to be renamed.

**Comment by munrocket** [comment] 2021-07-01 20:16
This is legal operation in WGSL?

**Comment by kvark** [comment] 2021-07-02 02:37
No, it's not legal. Closing as dupe of  #1044

**Comment by kvark** [comment] 2021-07-02 02:38
I'm surprised MSL outputs this, actually. It uses the `Namer` to assign unique names 🤔 
So may be a bug in msl-out.

**Comment by teoxoy** [comment] 2022-04-29 10:58
The msl output is correct (no duplicates) as of current master. I tried to reproduce the issue with all released versions of naga without success.

@superdump do you still have this issue? There might be something else that's not working.

**Comment by teoxoy** [comment] 2022-06-16 07:51
Let's close this for now, feel free to reopen if the issue is still present.

**Closed by teoxoy** 2022-06-16 07:51 UTC
Labels: kind: bug, lang: Metal, area: back-end
