### ISSUE TITLE
extractBits unimplemented

### ISSUE THREAD

**Issue by Brad-Hesson** [gfx-rs/naga#2365] opened 2023-06-01 22:20 UTC
Got the following error during compilation using WGPU
```
2023-06-01T22:10:20.973603Z ERROR wgpu::backend::direct: Shader translation error for stage ShaderStages(NONE | VERTEX): HLSL: Unimplemented("write_expr_math ExtractBits")
2023-06-01T22:10:20.973856Z ERROR wgpu::backend::direct: Please report it to https://github.com/gfx-rs/naga
2023-06-01T22:10:20.974506Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `Render Pipeline`
    Internal error in ShaderStages(NONE | VERTEX) shader: HLSL: Unimplemented("write_expr_math ExtractBits")

'
```

This is the code:
```rust
@vertex
fn vs_main(
    vertex: VertexInput,
    @location(2) instance: u32,
    @location(3) color: u32
) -> VertexOutput {
    var coords = vec2<f32>(hilbert_decode(instance, N));
    coords = coords / f32(1u << 16u) * 2. - 1.;
    var pos = vertex.position.xy;
    pos = pos / f32(1u << 16u) + coords;
    pos += pan_zoom.pan;
    pos *= pan_zoom.zoom;
    var out: VertexOutput;
    out.color = vec4<f32>(
        f32(extractBits(color, 0u, 8u)),
        f32(extractBits(color, 8u, 8u)),
        f32(extractBits(color, 16u, 8u)),
        f32(extractBits(color, 24u, 8u))
    );
    out.clip_position = vec4<f32>(pos, 1., 1.0);
    return out;
}
```

**Comment by cwfitzgerald** [comment] 2023-06-01 22:26
Duplicate of https://github.com/gfx-rs/naga/issues/1929
Will be solved by https://github.com/gfx-rs/naga/issues/1929

**Comment by Brad-Hesson** [comment] 2023-06-01 22:27
my bad, should've searched hard for an existing issue.  Thanks

**Closed by cwfitzgerald** 2023-06-01 22:26 UTC
