### ISSUE TITLE
Target languages

### ISSUE THREAD

**Issue by icefoxen** [gfx-rs/naga#1] opened 2019-01-21 16:29 UTC
Writing what is, essentially a SPIRV-to-whatever compiler sounds like fun!  What are our specific targets for "whatever"?

 * MSL
 * HLSL
 * GLSL -- which heckin' versions???  Want to run on OpenGL Desktop, ES and WebGL, I assume.
 * SPIRV -- tautologically
 * Anything else?

**Comment by kvark** [comment] 2019-01-22 02:59
https://github.com/gpuweb/WHLSL would be another target

Note that for each of those we'd have sub-version targets, i.e. MSL-1.1, MSL-2.0, MSL-2.1, and GLSL-ES-2.0, GLSL-ES-3.0, GLSL-4.4, etc

**Comment by fryeb** [comment] 2020-03-09 05:51
Would a x86_64 or ARM back-end be worth pursuing? (possibly using something like [cranelift](https://github.com/bytecodealliance/wasmtime/tree/master/cranelift)?). Doing so might help with a future software implementation of gfx-rs if that is something people are interested in.

**Comment by kvark** [comment] 2020-03-09 16:51
@fryeb that would be absolutely terrific! The problem is that the amount of work for this is comparable to the rest of the scope of the project, and it's hardly a priority. So if you are going to be developing a cranelift, we'd happily accept it in the project.

**Comment by jrmuizel** [comment] 2020-03-09 17:02
FWIW, depending on your situation it may be easier to compile the shaders to C++. That's what we're doing for WebRender based on https://github.com/jrmuizel/glsl-to-cxx

**Comment by kvark** [comment] 2020-09-19 04:22
Going to close this as mostly answered, and abstract. Please feel free to continue discussion or open more concrete issues!

Note that GLSL backend has been worked on by @JCapucho . It's already at a stage where it can convert the `boids` example and validate successfully.

**Closed by kvark** 2020-09-19 04:22 UTC
Labels: kind: question
