### ISSUE TITLE
Texture Sampling Error

### ISSUE THREAD

**Issue by RebelAndroid** [gfx-rs/naga#2030] opened 2022-08-18 21:35 UTC
I have this shader:
```
// visibility buffer texture
@group(0) @binding(0)
var visibility_buffer: texture_2d<u32>;
// counters
@group(0) @binding(1)
var<storage, read_write> counters: array<atomic<u32>>;

// maps model ids to shaders, ie. if model_shader_map[12] == 1 then the model with id 12 uses shader 1
@group(0) @binding(2)
var<storage> model_shader_map: array<u32>;

@compute @workgroup_size(1u)
fn count_shaders(@builtin(global_invocation_id) coord: vec3<u32>){
    let sample_pos: vec2<u32> = coord.xy;
    let visibility = textureLoad(visibility_buffer, sample_pos, 0u);
    let model = visibility.x >> 8u;
    let shader = model_shader_map[model];
    atomicAdd(counters[shader], 1);
}
```
When I try to use it I get the following error:
```
Shader validation error: 
   ┌─ opaque visibility shader module:17:21
   │
17 │     let visibility = textureLoad(visibility_buffer, sample_pos, 0u);
   │                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ naga::Expression [7]


    Entry point count_shaders at Compute is invalid
    Expression [7] is invalid
    Image coordinate type of [5] does not match dimension D2
```

According to [this documentation](https://gpuweb.github.io/gpuweb/wgsl/#textureload) the second parameter of textureLoad for a texture_2d should be a vec2\<u32\> or a vec2\<i32\> and I am passing in a vec2\<u32\> so why doesn't this work? I am almost entirely sure that I am doing something wrong here but I don't now what it is and I would be very grateful if someone could explain it to me.

**Comment by JCapucho** [comment] 2022-08-21 12:55
This is a duplicate of #1997

**Closed by JCapucho** 2022-08-21 12:55 UTC
