### ISSUE TITLE
Shader translation error for stage FRAGMENT with Bevy

### ISSUE THREAD

**Issue by jivvy** [gfx-rs/naga#2275] opened 2023-03-13 19:51 UTC
When running bevy on wayland, the following error comes up.

(in bevy repo:)
```
❯ WGPU_BACKEND=gl WINIT_UNIX_BACKEND=wayland cargo run --example lighting
```
```
2023-03-13T19:46:16.134376Z  INFO bevy_render::renderer: AdapterInfo { name: "llvmpipe (LLVM 15.0.7, 256 bits)", vendor: 0, device: 0, device_type: Cpu, backend: Gl }
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
2023-03-13T19:46:16.345607Z ERROR wgpu::backend::direct: Shader translation error for stage FRAGMENT: gsamplerCubeArrayShadow isn't supported in textureGrad, textureLod or texture with bias
2023-03-13T19:46:16.345632Z ERROR wgpu::backend::direct: Please report it to https://github.com/gfx-rs/naga
2023-03-13T19:46:16.345658Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `pbr_opaque_mesh_pipeline`
    Internal error in FRAGMENT shader: gsamplerCubeArrayShadow isn't supported in textureGrad, textureLod or texture with bias

', /home/jivvy/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.13.1/src/backend/direct.rs:2391:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Error said to report it here, so I created this issue.

System:
Arch Linux 64 bit
AMD 6700 XT with `mesa`, `amdvlk`, `vulkan-radeon`
sway/Wayland

**Comment by teoxoy** [comment] 2023-03-14 10:21
I think this is a limitation of the glsl backend and there isn't much we can do about it.
@JCapucho thoughts on this?

**Comment by JCapucho** [comment] 2023-03-14 17:17
This is a duplicate of #1619 and as explained in that issue, the only option is to possibly enable the [EXT_texture_shadow_lod](https://registry.khronos.org/OpenGL/extensions/EXT/EXT_texture_shadow_lod.txt) extension, which is not guaranteed to be available and is not available for webgl.

**Comment by teoxoy** [comment] 2023-03-14 17:39
Thanks! I missed that issue. Closing as duplicate.

**Closed by teoxoy** 2023-03-14 17:39 UTC
Labels: lang: GLSL
