### ISSUE TITLE
hlsl-out miscompilation of case with two selectors

### ISSUE THREAD

**Issue by raphlinus** [gfx-rs/naga#2136] opened 2022-11-28 05:28 UTC
I'm trying piet-wgsl with the DX12 backend. To repro, check out linebender/piet-gpu, apply the following diff, go to piet-wgsl/examples/winit, and cargo run.

```diff
--- a/piet-wgsl/src/util.rs
+++ b/piet-wgsl/src/util.rs
@@ -30,17 +30,16 @@ pub struct RenderContext {

 impl RenderContext {
     pub async fn new() -> Result<Self> {
-        let instance = Instance::new(wgpu::Backends::PRIMARY);
+        let instance = Instance::new(wgpu::Backends::DX12);
         let adapter = instance.request_adapter(&Default::default()).await.unwrap();
         let features = adapter.features();
         let mut limits = Limits::default();
-        limits.max_storage_buffers_per_shader_stage = 16;
+        limits.max_storage_buffers_per_shader_stage = 8;
         let (device, queue) = adapter
             .request_device(
                 &wgpu::DeviceDescriptor {
                     label: None,
-                    features: features
-                        & (wgpu::Features::TIMESTAMP_QUERY | wgpu::Features::CLEAR_TEXTURE),
+                    features,
                     limits,
                 },
                 None,
```

The shader being miscompiled is [draw_leaf.wgsl](https://github.com/linebender/piet-gpu/blob/main/piet-wgsl/shader/draw_leaf.wgsl) (there's a bit of templating being applied). The relevant input is lines 127..129:

```wgsl
            case 0x44u, 0x48u: {
                info[di] = bitcast<u32>(linewidth);
            }
```

The output is:

```hlsl
            case 68u: {
                {
                }
                {
                    float _expr172 = linewidth;
                    info.Store(di*4, asuint(uint(_expr172)));
                }
                break;
            }
            case 72u: {
                float _expr172 = _expr172;
                info.Store(di*4, asuint(uint(_expr172)));
                break;
            }
```

D3DCompiler reasonably refuses to compile this (complaining that _expr172 is undefined).

Note that this isn't expected to actually run, as the limit of 8 storage buffers currently prevents coarse from running. We'll do a workaround for that, but I did want to see how far it would get.

**Comment by teoxoy** [comment] 2022-11-28 12:21
This looks like a duplicate of #1972. Should be fixed as soon as we land the switch PRs.

**Closed by teoxoy** 2022-11-28 12:21 UTC
