### ISSUE TITLE
InvalidGlobalVar(LocalVariable([2])) while SPIR-V creating shader module using wgpu-native

### ISSUE THREAD

**Issue by ryhor-spivak** [gfx-rs/naga#1421] opened 2021-09-24 10:17 UTC
I'm getting this crash while trying to load this fragment shader with wgpuDeviceCreateShaderModule from wgpu-native
[1.frag.zip](https://github.com/gfx-rs/naga/files/7224825/1.frag.zip)

This SPIR-V is compiled from this GLSL with glslangValidator without optimizations (glslangValidator -V -o 1.frag.spv 1.frag):

```
#version 450
precision mediump float;
layout(location = 0)out vec4 F;
layout(location = 0)in vec2 var_uv;
layout(set = 1, binding = 0)uniform texture2D tex;
layout(set = 1, binding = 1)uniform sampler smplr;
vec4 lookup(vec2 uv, texture2D t, sampler s){
	return texture(sampler2D(t, s), uv);
}
vec4 lookupMix(vec2 uv, float factor, texture2D t, sampler s){
	vec4 color = lookup(uv, t, s);
	return mix(uv.xyxy, color, factor);
}
void main(){
	F = lookupMix(var_uv, var_uv.x, tex, smplr);
}
```

By stepping through the code in the debugger I can see this error is coming from here:
https://github.com/gfx-rs/naga/blob/300039e24703bc823cc932985947dfda66616e1e/src/front/spv/mod.rs#L2340

patch_statements being called by patch_function on "main" from this shader. Unfortunately, I don't have enough Rust skills to understand what is wrong here.

**Comment by kvark** [comment] 2021-09-25 16:16
Thank you for filing!
It's complaining about passing a texture into a function as a parameter. This is fixed in latest Naga, so it's a matter of updating wgpu-native.

**Comment by kvark** [comment] 2021-09-25 16:17
You can check it yourself by running Naga cli:
```
graphics35334:naga dmalyshau$ cargo run -- ~/Downloads/1.frag.spv 
   Compiling naga v0.6.0 (/Users/dmalyshau/Code/naga)
   Compiling naga-cli v0.4.0 (/Users/dmalyshau/Code/naga/cli)
    Finished dev [unoptimized + debuginfo] target(s) in 18.47s
     Running `target/debug/naga /Users/dmalyshau/Downloads/1.frag.spv`
Validation successful
```

**Comment by JCapucho** [comment] 2021-09-25 16:19
@kvark this doesn't seem to be the case here, it seems like spir-v is passing the texture trough a local variable, this was a thing that I noticed could and brought up in the matrix room.

**Comment by JCapucho** [comment] 2021-09-25 16:21
But you're right the provided shader passes validation so the error message is strange

**Comment by kvark** [comment] 2021-09-25 16:48
The panic was in spv-in (not even validation), and it's definitely working on both Naga master and v0.6. So I don't think the issue is actionable here. wgpu-native just needs to update.

**Comment by JCapucho** [comment] 2021-09-25 17:06
Yeah the problem in this shader was that, I'll open up another issue with the shader I'm talking about so that you can see the problem.

**Closed by JCapucho** 2021-09-25 17:06 UTC
