### ISSUE TITLE
Use of flat fragment shader inputs treated as non-uniform control flow

### ISSUE THREAD

**Issue by fintelia** [gfx-rs/naga#1236] opened 2021-08-19 04:46 UTC
This shader code:
```glsl
#version 450 core

layout(set = 0, binding = 0) uniform sampler linear;
layout(set = 0, binding = 1) uniform texture2D normals;

layout(location = 0) flat in int i;

void main() {
    if (i == 0)
        vec4 v = texture(sampler2D(normals, linear), vec2(0));
}
```
produces this validation error:
```
Function [1] 'main' is invalid: 
	Required uniformity of control flow for IMPLICIT_LEVEL in [13] is not fulfilled because of Expression([3])
```

**Comment by cwfitzgerald** [comment] 2021-08-19 05:19
Unfortunately, Naga is right here. Quads from different triangles can and do end up in the same warp, and as such this is actually non-uniform control flow within the warp.

This is the unfortunate part though, as on real hardware, using derivatives in a non-uniform context is only UB if it is non-uniform within a quad, not within a wave. However, as I understand it, spirv, as a compilation target, has no concept of quad uniformity. Therefore, per the spec, it's UB if you use derivatives in any non-uniform control flow at all.

I've hit this many times myself and want to figure a way to open up conformity analysis to allow this code as a native extension, but that requires a fairly in depth investigation as to if we can really get away with it and likely a good chunk of work in Naga.

**Comment by cwfitzgerald** [comment] 2021-08-19 05:23
I'm going to close this for now, but I'm going to file a feature proposal against wgpu to see what we can do about this.

**Closed by cwfitzgerald** 2021-08-19 05:23 UTC

**Comment by kvark** [comment] 2021-08-19 13:26
SPIR-V does mention quad-uniformity, and maybe even defines where it diverges. But the problem is re-convergence: SPIR-V currently defines re-convergence only at the scope of the whole draw call. So if WebGPU gets this rule more tightly checked, it may end up with some weird semantic where your code may suddenly become invalid based on what you did before the sampling, even if that other code should have re-converged. TL;DR: it's quite complicated.

One other possibility is just having a native-only feature that disables uniformity checks. That would be easy to get in.

**Comment by fintelia** [comment] 2021-08-19 14:58
Hm, that is frustrating. Is there any way to work around it if the value is actually known to be uniform across more than just individual triangles? In my particular case the value I'm trying to pass is actually gl_InstanceIndex, I'd expect there to be no issues with warp non-uniformity if I could just communicate that to naga.

**Comment by kvark** [comment] 2021-08-19 16:54
@fintelia in general using `gl_InstanceIndex` doesn't guarantee that get the quad uniformity. E.g.:
```
if (MyFlatInterpolatedStuff) {
  if (gl_FragCoord.x == 0) {
    // do something
  }
  // this is no longer quad-uniform!
}
```

According to SPIR-V today, the control flow after `gl_FragCoord` check will not re-converge until it's uniform across the whole draw again. So it's not just a matter of communicating to Naga, it's a set of non-trivial safety constraints that we need to obey, and currently the checks are on the conservative side.

Ideally, you'd not write the code that risks being non-portable this way. But if you have to, we'll need to think of a way to disable the uniformity analysis entirely on native, as a workaround.

**Comment by fintelia** [comment] 2021-08-19 19:56
@cwfitzgerald wrote:
> However, as I understand it, spirv, as a compilation target, has no concept of quad uniformity. Therefore, per the spec, it's UB if you use derivatives in any non-uniform control flow at all.

The current version of the spec talks about Derivative Groups which might be what you want...
> Derivative Group: Defined only for the Fragment Execution Model: The set of invocations collectively processing
derivatives, which is at most as large as a single point, line, or triangle, including any helper invocations, as defined by the
client API.

> Derivatives appear only in the Fragment Execution Model. They are either implicit or explicit. Some image instructions
consume implicit derivatives, while the derivative instructions compute explicit derivatives. In all cases, derivatives are well defined when the derivative group has uniform control flow, otherwise see the client API specification for what
behavior is allowed.
