### ISSUE TITLE
[spv-in] assertion failed: prev.is_none()

### ISSUE THREAD

**Issue by fintelia** [gfx-rs/naga#1927] opened 2022-05-15 17:46 UTC
This GLSL shader when converted to SPIR-V ([shader.spv.zip](https://github.com/gfx-rs/naga/files/8695593/shader.spv.zip)):
```glsl
#version 460 core

void main() {
    do{}while(false);
}
```
Produces this assertion failure when compiled with naga:
```
thread 'main' panicked at 'assertion failed: prev.is_none()', src/front/spv/mod.rs:3080:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/core/src/panicking.rs:48:5
   3: naga::front::spv::Parser<I>::next_block
             at ./src/front/spv/mod.rs:3080:25
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted
```

**Comment by JCapucho** [comment] 2022-05-17 20:08
This is a duplicate of #1900

**Closed by JCapucho** 2022-05-17 20:08 UTC
Labels: kind: bug, lang: SPIR-V, area: front-end
