### ISSUE TITLE
[wgsl-in] allow functions to be declared literally after entry point

### ISSUE THREAD

**Issue by vicary** [gfx-rs/naga#2072] opened 2022-09-30 08:37 UTC
This is discovered in Deno when using tensorflow.js with its WebGPU backend, when tfjs declares a function `fn main` after the entry point `fn _start`. The generated WGSL works in Chrome Canary 108.0.5329.0 (V8 10.8.79) but fails in Deno, error details at https://github.com/tensorflow/tfjs/issues/6842#issuecomment-1262708937.

Experiments in https://github.com/tensorflow/tfjs/issues/6842#issuecomment-1263196772 showed that in naga, invoked functions have to be declared literally before the entry point and the `@compute` directive.

The current WGSL specification (20220922) seems to have [function scoping](https://www.w3.org/TR/2022/WD-WGSL-20220922/#function-declaration-sec), replacing the [lexical scoping](https://github.com/gpuweb/gpuweb/issues/559) back in 2020.

> A function declaration [must](https://www.w3.org/TR/2022/WD-WGSL-20220922/#shader-creation-error) only occur at [module scope](https://www.w3.org/TR/2022/WD-WGSL-20220922/#module-scope). A function name is [in scope](https://www.w3.org/TR/2022/WD-WGSL-20220922/#in-scope) for the entire program.

Given the generated script [shader.wgsl](https://github.com/gfx-rs/naga/files/9682291/shader.wgsl.txt), should the function `main` be available in scope when `_start` is invoked?

**Comment by SparkyPotato** [comment] 2022-09-30 18:52
This is a limitation of the current WGSL front end.
It will be fixed with #2065.

**Comment by teoxoy** [comment] 2022-11-15 18:58
Closing as duplicate of #1745.

**Closed by teoxoy** 2022-11-15 18:58 UTC
Labels: kind: bug, lang: WGSL, area: front-end
