### ISSUE TITLE
Spanned errors for validation stage

### ISSUE THREAD

**Issue by hcsch** [gfx-rs/naga#1225] opened 2021-08-18 18:49 UTC
Currently only the parsing stage seems to support spanned errors (showing a bit of source context in the error message, underlining and coloring what is relevant).

The validation stage reports errors mainly as messages referencing syntactical objects via their handle pointing into the arena (i.e. just as a number that is hard to match to a particular part of the source).
Some parts of the validation stage also log errors, which usually make finding the context of the error in the source a bit easier, but even with these, locating an error in the source is not very easy. The best clue you get is usually the name of the function and the type of the statement / expression.

For example, the following (extracted snippet of) code:
```wgsl
fn draw_orbit(starting_num: vec2<f32>, worker_state: WorkerState,
                nums_left_to_draw: i32) -> DrawOrbitResult {
    var finished = false;

    var z: vec2<f32> = worker_state.cur_orbit_last_drawn_num;
    var i: i32;
    for (i = worker_state.cur_orbit_nums_drawn;
         i <
         min(worker_state.cur_orbit_nums_drawn + nums_left_to_draw, config.max_iters_total);
         i = i + 1) {
        z = bbrot_step(z, starting_num);
        if (dot(z, z) > config.escape_radius_squared) {
            finished = true;
            break; // done.
        }
        if (is_num_in_image(z)) {
            add_to_pixel_of_num(z, vec3<u32>(u32(i < config.max_iters.r), u32(i < config.max_iters.g),
                                         u32(i < config.max_iters.b)));
        }
    }
    if (finished) {
        let nums_drawn_this_dispatch = i - worker_state.cur_orbit_nums_drawn;
        // nums_drawn_this_dispatch <= nums_left_to_draw should be true here
        return DrawOrbitResult(worker_state, nums_left_to_draw - nums_drawn_this_dispatch, finished);
    } else {
        worker_state.cur_orbit_nums_drawn = worker_state.cur_orbit_nums_drawn + nums_left_to_draw;
        worker_state.cur_orbit_last_drawn_num = z;
        return DrawOrbitResult(worker_state, 0, finished);
    }
}
```
gets me this error:
```
Function [14] 'draw_orbit' is invalid: 
	Store of [74] into [72] doesn't have matching types
```
This tells me I have to look at stores in the function `draw_orbit`, but there are quite a few stores in this function and having to manually type check all of them to find the wrong one gets tedious for longer functions.

**Comment by kvark** [comment] 2021-08-18 18:55
Sorry, this is a dupe of #358, which is pinned. Luckily, it's being looked at!

**Comment by hcsch** [comment] 2021-08-18 18:56
> Sorry, this is a dupe of #358, which is pinned. Luckily, it's being looked at!

Ah, sorry. I read through that and had assumed that issue concerns the parsing stage only.

**Closed by kvark** 2021-08-18 18:55 UTC

**Comment by ElectronicRU** [comment] 2021-08-18 19:04
Hey @hcsch,
I was wondering if you'd be okay with using your code snipped here, or a reduced version of such, as a test case.

**Comment by hcsch** [comment] 2021-08-18 19:16
> I was wondering if you'd be okay with using your code snipped here, or a reduced version of such, as a test case.

Sure, I'd be fine with that. I can even add the necessary context required (i.e. structs and function definitions) if you'd like. You can however also just cut the function calls and struct usages down to some dummies or something like that.
I would also be happy to provide the full shader, but I'm still in the sage of finding errors in my GLSL → WGSL port (and the shader in general might not be the prettiest, both in logic and syntax).
Feel free to tell me which of those options you'd like.

**Comment by hcsch** [comment] 2021-08-18 19:27
Here are all parts of the shader required for `draw_orbit` to be valid AFAICT (though not the full shader, that would require the PRNG code for starting number generation):
```wgsl
[[block]]
struct Config {
    img_size: vec2<i32>;
    max_iters: vec3<i32>;
    max_iters_total: i32;
    min_iters: i32;
    escape_radius_squared: f32;
    num_to_draw_per_dispatch: i32;
    rand_seed: u32;
};

[[block]]
struct CountsBuf {
    counts: array<atomic<u32>>;
};

struct WorkerState {
    total_samples_computed: u32;
    sampling_stage: u32;
    cur_orbit_nums_drawn: i32;
    cur_orbit_last_drawn_num: vec2<f32>;
};

[[group(0), binding(0)]] var<uniform> config: Config;
[[group(0), binding(1)]] var<storage, read_write> cbuf: CountsBuf;

var min_num: vec2<f32>;
var max_num: vec2<f32>;

fn add_to_pixel(pixel: vec2<i32>, to_add_rgb: vec3<u32>) {
    // TODO: check if preventing atomic add if component is eq 0 is faster than
    // always adding
    // TODO: possibly batch atomic adds somehow
    let offset = (pixel.x + pixel.y * config.img_size.x) * 3;
    if (to_add_rgb.r > 0u) {
        let _old_value = atomicAdd(&cbuf.counts[offset], to_add_rgb.r);
    }
    if (to_add_rgb.g > 0u) {
        let _old_value = atomicAdd(&cbuf.counts[offset + 1], to_add_rgb.g);
    }
    if (to_add_rgb.b > 0u) {
        let _old_value = atomicAdd(&cbuf.counts[offset + 2], to_add_rgb.b);
    }
}

fn is_num_in_image(z: vec2<f32>) -> bool {
    return z.x > min_num.x && z.y > min_num.y && z.x < max_num.x &&
           z.y < max_num.y;
}

fn pixel_of_num(z: vec2<f32>) -> vec2<i32> {
    var uv =
        (z - min_num) / (max_num - min_num); // note: component-wise operations
    uv = clamp(uv, vec2<f32>(0.0), vec2<f32>(1.0));
    return vec2<i32>(i32(f32(config.img_size.x) * uv.x), i32(f32(config.img_size.y) * uv.y));
}

fn add_to_pixel_of_num(z: vec2<f32>, to_add_rgb: vec3<u32>) {
    add_to_pixel(pixel_of_num(z), to_add_rgb);
}

fn bbrot_step(z: vec2<f32>, c: vec2<f32>) -> vec2<f32> {
    return vec2<f32>(z.x * z.x - z.y * z.y, z.x * z.y * 2.0) + c;
}

struct DrawOrbitResult {
    worker_state: WorkerState;
    nums_left_to_draw: i32;
    finished: bool;
};

fn draw_orbit(starting_num: vec2<f32>, worker_state: WorkerState,
                nums_left_to_draw: i32) -> DrawOrbitResult {
    var finished = false;

    var z: vec2<f32> = worker_state.cur_orbit_last_drawn_num;
    var i: i32;
    for (i = worker_state.cur_orbit_nums_drawn;
         i <
         min(worker_state.cur_orbit_nums_drawn + nums_left_to_draw, config.max_iters_total);
         i = i + 1) {
        z = bbrot_step(z, starting_num);
        if (dot(z, z) > config.escape_radius_squared) {
            finished = true;
            break; // done.
        }
        if (is_num_in_image(z)) {
            add_to_pixel_of_num(z, vec3<u32>(u32(i < config.max_iters.r), u32(i < config.max_iters.g),
                                         u32(i < config.max_iters.b)));
        }
    }
    if (finished) {
        let nums_drawn_this_dispatch = i - worker_state.cur_orbit_nums_drawn;
        // nums_drawn_this_dispatch <= nums_left_to_draw should be true here
        return DrawOrbitResult(worker_state, nums_left_to_draw - nums_drawn_this_dispatch, finished);
    } else {
        worker_state.cur_orbit_nums_drawn = worker_state.cur_orbit_nums_drawn + nums_left_to_draw;
        worker_state.cur_orbit_last_drawn_num = z;
        return DrawOrbitResult(worker_state, 0, finished);
    }
}
```

**Comment by hcsch** [comment] 2021-08-18 20:53
I've found the issue:
```wgsl
fn assign_to_argument(a: vec2<f32>) {
    a = vec2<f32>(0.0);
}
```
I'm gonna open a separate issue for this, because the error you get:
```
Function [1] 'assign_to_argument' is invalid: 
	Store of [3] into [1] doesn't have matching types
```
could likely be more helpful in identifying that the issue is assignment to a function argument.
