### ISSUE TITLE
Index out of bounds in validator

### ISSUE THREAD

**Issue by Sineaggi** [gfx-rs/naga#571] opened 2021-03-14 16:32 UTC
Call stack
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 1', /Users/cwalker/.cargo/git/checkouts/naga-dbb2b19faed49210/32a1175/src/proc/analyzer.rs:481:53
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:69:5
   3: naga::proc::analyzer::FunctionInfo::process_expression
             at /Users/cwalker/.cargo/git/checkouts/naga-dbb2b19faed49210/32a1175/src/proc/analyzer.rs:481:53
   4: naga::proc::analyzer::Analysis::process_function
             at /Users/cwalker/.cargo/git/checkouts/naga-dbb2b19faed49210/32a1175/src/proc/analyzer.rs:670:13
   5: naga::proc::analyzer::Analysis::new
             at /Users/cwalker/.cargo/git/checkouts/naga-dbb2b19faed49210/32a1175/src/proc/analyzer.rs:693:24
   6: naga::proc::validator::Validator::validate
             at /Users/cwalker/.cargo/git/checkouts/naga-dbb2b19faed49210/32a1175/src/proc/validator.rs:1212:24
   7: parser_repro::main
             at ./src/main.rs:8:5
```

File [from wpgu-native example](https://github.com/gfx-rs/wgpu-native/blob/master/examples/data/collatz.comp.spv)

**Comment by kvark** [comment] 2021-03-15 00:38
Investigated this and concluded to be a dupe of #573. Looks like it's very important to address ASAP.

**Closed by kvark** 2021-03-15 00:38 UTC
