### ISSUE TITLE
[wgsl-in] vector constructor and splat constructors require decimal point for float types

### ISSUE THREAD

**Issue by neilsarkar** [gfx-rs/naga#2518] opened 2023-09-27 13:34 UTC
```wgsl
@vertex fn vs(
  @location(0) pos: vec4f,
  @builtin(vertex_index) vertexIndex : u32
) -> @builtin(position) vec4f {
  return pos;
}

@fragment fn fs() -> @location(0) vec4f {
  return vec4f(1, 0, 1, 1);
}
```

this gives an error: 

```bash
Shader validation error: 
  ┌─ Hello World Shader:9:10
  │
9 │   return vec4f(1, 0, 1, 1);
  │          ^^^^^^^^^^^^^^^^^ naga::Expression [5]


    Entry point fs at Fragment is invalid
    Expression [5] is invalid
    Composing 0's component type is not expected
```

this can be fixed by changing the line to:

```wgsl
return vec4f(1.0, 0.0, 1.0, 1.0);
```

this is unexpected coming from native webgpu in the browser, where `vec4f(1,0,1,1)` will correctly render magenta.

it seems to be described in the wgsl spec here: https://www.w3.org/TR/WGSL/#conversion-rank

is the divergence intentional? or is it something we want to catch up to in the wgsl spec?

**Comment by teoxoy** [comment] 2023-09-27 20:16
Thanks for the report, this is not yet implemented.
Closing as duplicate of https://github.com/gfx-rs/naga/issues/2127.

**Closed by teoxoy** 2023-09-27 20:16 UTC
