### ISSUE TITLE
ANSI escape codes in error messages in Firefox

### ISSUE THREAD

**Issue by Kangz** [gfx-rs/naga#2278] opened 2023-03-15 00:01 UTC
Trying to fixup the webgpu-samples to run in Firefox I got the following error message from Naga:

```
Shader validation �[0m�[1m�[38;5;9merror�[0m�[1m: �[0m
   �[0m�[34m┌─�[0m :55:7
   �[0m�[34m│�[0m
�[0m�[34m55�[0m �[0m�[34m│�[0m   if (�[0m�[31mcMassCount > 0�[0m) {
   �[0m�[34m│�[0m       �[0m�[31m^^^^^^^^^^^^^^�[0m �[0m�[31mnaga::Expression [100]�[0m
```

The ANSI escape codes are adding a TON of noise that make it hard to understand what the issue is. If needed I can try to roll back my changes to retrieve the shader that was causing the issue. Let me know.

**Comment by jimblandy** [comment] 2023-03-15 01:29
Thanks for filing this. I can reproduce this locally.

It only seems to apply to errors from Naga validation; WGSL front end errors are all right:

```
Shader '' parsing error: unknown attribute: 'vertexx'
  ┌─ wgsl:4:2
  │
4 │ @vertexx
  │  ^^^^^^^ unknown attribute
```

**Comment by jimblandy** [comment] 2023-03-15 01:41
The problem actually seems to be [in `wgpu`](https://github.com/gfx-rs/wgpu/blob/42a0683d487f63a802d4927c799306c5adf891b2/wgpu-core/src/pipeline.rs#L91):

```
        let mut writer = term::termcolor::Ansi::new(Vec::new());
```

**Comment by teoxoy** [comment] 2023-03-15 08:58
Fixed in https://github.com/gfx-rs/wgpu/pull/3591

**Closed by teoxoy** 2023-03-15 08:58 UTC
Labels: kind: bug, area: validation, kind: diagnostics
